### ISSUE TITLE
Fireworks not rendering graph in workflow view

### ISSUE THREAD

**Issue by sivonxay** [materialsproject/workshop#23]
The following error is thrown when trying to view the workflow page in the fireworks webgui.

Looking into this now, just wanted to document it in case someone else knows the issue.

`[2019-07-29 20:01:24,205] ERROR in app: Exception on /fireworks/wf/2/json [GET]
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fireworks/flask_site/app.py", line 77, in decorated
    return f(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fireworks/flask_site/app.py", line 229, in workflow_json
    return jsonify(nodes_and_edges)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fireworks/flask_site/util.py", line 38, in jsonify
    dumps(data, indent=indent, separators=separators, cls=MongoJsonEncoder) + '\n',
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'encoding'`

**Comment by sivonxay** [comment]
Looks like there was some change in fireworks after commit fe9b4f25f7398df18554356380a78ab82fb8bb95 that causes this issue.

I suspect it is commit 200595894af8268d390717bc2662e1dc9d2d2687, but i'm trying to verify this.

The simple fix (if it doesn't break anything else) would be to roll back to that working commit.

**Comment by tschaume** [comment]
closed via tschaume/fireworks@621e0f0a2ce6bf4d14c9cf0a421a17b3470f4d37
